// flow-typed signature: caeaa8255203fee7107e3e5c0cce7455
// flow-typed version: <<STUB>>/react-sizeme_v^2.3.6/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sizeme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sizeme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sizeme/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-sizeme/commonjs/resizeDetector' {
  declare module.exports: any;
}

declare module 'react-sizeme/commonjs/sizeMe' {
  declare module.exports: any;
}

declare module 'react-sizeme/umd/react-sizeme' {
  declare module.exports: any;
}

declare module 'react-sizeme/umd/react-sizeme.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sizeme/commonjs/index.js' {
  declare module.exports: $Exports<'react-sizeme/commonjs/index'>;
}
declare module 'react-sizeme/commonjs/resizeDetector.js' {
  declare module.exports: $Exports<'react-sizeme/commonjs/resizeDetector'>;
}
declare module 'react-sizeme/commonjs/sizeMe.js' {
  declare module.exports: $Exports<'react-sizeme/commonjs/sizeMe'>;
}
declare module 'react-sizeme/umd/react-sizeme.js' {
  declare module.exports: $Exports<'react-sizeme/umd/react-sizeme'>;
}
declare module 'react-sizeme/umd/react-sizeme.min.js' {
  declare module.exports: $Exports<'react-sizeme/umd/react-sizeme.min'>;
}
