// flow-typed signature: b29989fc653105dd65a5a0b45cd3e36f
// flow-typed version: <<STUB>>/@vx/axis_v^0.0.158/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/axis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/axis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/axis/build/axis/Axis' {
  declare module.exports: any;
}

declare module '@vx/axis/build/axis/AxisBottom' {
  declare module.exports: any;
}

declare module '@vx/axis/build/axis/AxisLeft' {
  declare module.exports: any;
}

declare module '@vx/axis/build/axis/AxisRight' {
  declare module.exports: any;
}

declare module '@vx/axis/build/axis/AxisTop' {
  declare module.exports: any;
}

declare module '@vx/axis/build/constants/orientation' {
  declare module.exports: any;
}

declare module '@vx/axis/build/index' {
  declare module.exports: any;
}

declare module '@vx/axis/build/utils/center' {
  declare module.exports: any;
}

declare module '@vx/axis/build/utils/identity' {
  declare module.exports: any;
}

declare module '@vx/axis/build/utils/isHorizontal' {
  declare module.exports: any;
}

declare module '@vx/axis/build/utils/isLeft' {
  declare module.exports: any;
}

declare module '@vx/axis/build/utils/labelTransform' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/axis/build/axis/Axis.js' {
  declare module.exports: $Exports<'@vx/axis/build/axis/Axis'>;
}
declare module '@vx/axis/build/axis/AxisBottom.js' {
  declare module.exports: $Exports<'@vx/axis/build/axis/AxisBottom'>;
}
declare module '@vx/axis/build/axis/AxisLeft.js' {
  declare module.exports: $Exports<'@vx/axis/build/axis/AxisLeft'>;
}
declare module '@vx/axis/build/axis/AxisRight.js' {
  declare module.exports: $Exports<'@vx/axis/build/axis/AxisRight'>;
}
declare module '@vx/axis/build/axis/AxisTop.js' {
  declare module.exports: $Exports<'@vx/axis/build/axis/AxisTop'>;
}
declare module '@vx/axis/build/constants/orientation.js' {
  declare module.exports: $Exports<'@vx/axis/build/constants/orientation'>;
}
declare module '@vx/axis/build/index.js' {
  declare module.exports: $Exports<'@vx/axis/build/index'>;
}
declare module '@vx/axis/build/utils/center.js' {
  declare module.exports: $Exports<'@vx/axis/build/utils/center'>;
}
declare module '@vx/axis/build/utils/identity.js' {
  declare module.exports: $Exports<'@vx/axis/build/utils/identity'>;
}
declare module '@vx/axis/build/utils/isHorizontal.js' {
  declare module.exports: $Exports<'@vx/axis/build/utils/isHorizontal'>;
}
declare module '@vx/axis/build/utils/isLeft.js' {
  declare module.exports: $Exports<'@vx/axis/build/utils/isLeft'>;
}
declare module '@vx/axis/build/utils/labelTransform.js' {
  declare module.exports: $Exports<'@vx/axis/build/utils/labelTransform'>;
}
