// flow-typed signature: 6f2286ed76c6b96417cbbd9b6553905a
// flow-typed version: <<STUB>>/@vx/bounds_v^0.0.153/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/bounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/bounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/bounds/build/enhancers/withBoundingRects' {
  declare module.exports: any;
}

declare module '@vx/bounds/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/bounds/build/enhancers/withBoundingRects.js' {
  declare module.exports: $Exports<'@vx/bounds/build/enhancers/withBoundingRects'>;
}
declare module '@vx/bounds/build/index.js' {
  declare module.exports: $Exports<'@vx/bounds/build/index'>;
}
