// flow-typed signature: fa025d0bd0da49fe6fa05b827abe93eb
// flow-typed version: <<STUB>>/@vx/curve_v^0.0.153/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/curve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/curve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/curve/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/curve/build/index.js' {
  declare module.exports: $Exports<'@vx/curve/build/index'>;
}
