// flow-typed signature: 54a7893b62d3ab01e778c00f8c10e03b
// flow-typed version: <<STUB>>/@vx/group_v^0.0.153/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/group/build/Group' {
  declare module.exports: any;
}

declare module '@vx/group/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/group/build/Group.js' {
  declare module.exports: $Exports<'@vx/group/build/Group'>;
}
declare module '@vx/group/build/index.js' {
  declare module.exports: $Exports<'@vx/group/build/index'>;
}
