// flow-typed signature: c3ed26a35935625c33d687a4488a4a6c
// flow-typed version: <<STUB>>/@vx/pattern_v^0.0.153/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/pattern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/pattern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/pattern/build/constants/index' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/index' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/patterns/Circles' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/patterns/Hexagons' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/patterns/Lines' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/patterns/Path' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/patterns/Pattern' {
  declare module.exports: any;
}

declare module '@vx/pattern/build/patterns/Waves' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/pattern/build/constants/index.js' {
  declare module.exports: $Exports<'@vx/pattern/build/constants/index'>;
}
declare module '@vx/pattern/build/index.js' {
  declare module.exports: $Exports<'@vx/pattern/build/index'>;
}
declare module '@vx/pattern/build/patterns/Circles.js' {
  declare module.exports: $Exports<'@vx/pattern/build/patterns/Circles'>;
}
declare module '@vx/pattern/build/patterns/Hexagons.js' {
  declare module.exports: $Exports<'@vx/pattern/build/patterns/Hexagons'>;
}
declare module '@vx/pattern/build/patterns/Lines.js' {
  declare module.exports: $Exports<'@vx/pattern/build/patterns/Lines'>;
}
declare module '@vx/pattern/build/patterns/Path.js' {
  declare module.exports: $Exports<'@vx/pattern/build/patterns/Path'>;
}
declare module '@vx/pattern/build/patterns/Pattern.js' {
  declare module.exports: $Exports<'@vx/pattern/build/patterns/Pattern'>;
}
declare module '@vx/pattern/build/patterns/Waves.js' {
  declare module.exports: $Exports<'@vx/pattern/build/patterns/Waves'>;
}
