// flow-typed signature: 523266815325f572f1b3a038758aac48
// flow-typed version: <<STUB>>/@vx/point_v^0.0.153/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/point'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/point' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/point/build/index' {
  declare module.exports: any;
}

declare module '@vx/point/build/Point' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/point/build/index.js' {
  declare module.exports: $Exports<'@vx/point/build/index'>;
}
declare module '@vx/point/build/Point.js' {
  declare module.exports: $Exports<'@vx/point/build/Point'>;
}
